# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'missvan' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for furniture
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'CropViewController'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON'

end